name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  synth:
    name: synth
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: synth
        run: npx cdk synth  >synth.txt 2>&1
        continue-on-error: true
      - name: "PR comment"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: CDK SYNTH
          path: synth.txt

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: test
        run: npm run test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: lint
        run: npm run lint
  diff:
    name: diff
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
      - name: diff
        run: npx cdk diff > diff.txt
      - name: "PR comment"
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: CDK DIFF
          path: diff.txt
