name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  synth:
    name: synth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: synth
        run: npx cdk synth
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: test
        run: npm run test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: lint
        run: npm run lint
  diff:
    name: diff
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci-environment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
      - name: diff
        run: npx cdk diff > diff.txt
      - name: Comment PR with CDK Diff
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('./diff.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `CDK Diff:\n\`\`\`shell\n${diff}\n\`\`\``
            });
